name: build
on: [push, pull_request]
jobs:
  test:
    strategy:
      matrix:
        go-version: [1.2.x, 1.3.x, 1.4.x, 1.5.x, 1.6.x, 1.7.x, 1.8.x, 1.9.x, 1.10.x, 1.11.x, 1.12.x, 1.13.x]
        platform: [ubuntu-latest]
    runs-on: ${{ matrix.platform }}
    env:
      GO111MODULE: "on"
      GOPATH: "/home/runner/go"
    steps:

    - name: Install Dependencies
      run: |
        sudo apt-get update -qq
        sudo apt-get install -y cracklib-runtime
      if: matrix.platform == 'ubuntu-latest'

    - name: Install Go
      uses: actions/setup-go@v1
      with:
        go-version: ${{ matrix.go-version }}

    - name: Checkout code
      uses: actions/checkout@v1

    - name: Build
      run: |
        go get -v
        go build -v ./...

    - name: Test
      run: go test ./...

    - name: Coverage
      env:
        COVERALLS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        go test -race -covermode atomic -coverprofile=profile.cov ./...
        GO111MODULE=off go get github.com/mattn/goveralls
        $(go env GOPATH)/bin/goveralls -coverprofile=profile.cov -service=github
      if: matrix.go-version == '1.13.x' && matrix.platform == 'ubuntu-latest'
